image:
  file: .gitpod/Dockerfile

tasks:
    - init: >
          gp open README.md;
      command: >
          gp open README.md;

ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - bazelbuild.vscode-bazel
    