name: "Dataset - Synchronize from GitHub"

on:
  schedule:
    - cron: "30 4 * * 4"
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/data.github.yml

jobs:
  dataset-synchronize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Synchronize the branch
        run: |
          bash scripts/sync.bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}