name: "jrbeverly.dev"
on:
  push:
    paths:
    - srv/jrbeverly.dev/**
    - .github/workflows/jrbeverly.dev.netlify.yml

jobs:
  hugo:
    name: build-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build & Package
        run: |
          bazel run //srv/jrbeverly.dev:publish
  
      - uses: docker://cardboardci/netlify:latest
        if: github.ref == 'refs/heads/master'
        with:
          args: "netlify deploy --dir srv/jrbeverly.dev/artifacts --site ${{ secrets.NETLIFY_JRBEVERLY_DEV }} --auth ${{ secrets.NETLIFY_TOKEN }} --prod"