name: "jrbeverly.dev"
on:
  push:
    paths:
    - srv/jrbeverly.dev/**
    - .github/workflows/jrbeverly.dev.netlify.yml

jobs:
  hugo:
    name: build-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build & Package
        run: |
          bazel run //srv/jrbeverly.dev:publish

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: netlify/jrbeverly.dev
          publish_dir: ./public/jrbeverly.dev